pipeline {
    agent any

    environment {
        GITHUB_CREDENTIALS = 'github-creds'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    credentialsId: "${GITHUB_CREDENTIALS}",
                    url: 'https://github.com/yourusername/messaging-app.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                python3 -m venv venv
                . venv/bin/activate
                pip install --upgrade pip
                pip install -r requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                . venv/bin/activate
                pytest --junitxml=reports/results.xml
                '''
            }
        }

        stage('Publish Test Report') {
            steps {
                junit 'reports/results.xml'
            }
        }
    }

    post {
        always {
            echo "Pipeline finished!"
        }
    }
}
