#!/bin/bash

echo "Scaling Django app deployment to 3 replicas..."
kubectl scale deployment django-app-deployment --replicas=3

echo "Verifying running pods..."
kubectl get pods -o wide

echo "Performing load testing using wrk..."
wrk -t4 -c100 -d30s http://localhost:8000/

echo "Monitoring resource usage..."
kubectl top pods

echo "Done!"
