# Generated by Django 5.2.6 on 2025-09-17 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='sender_id',
            new_name='participants_id',
        ),
    ]
