# Generated by Django 5.2.6 on 2025-09-17 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_rename_sender_id_conversation_participants_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='participants_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
