#!/bin/bash

set -e

echo "Applying Blue Deployment..."
kubectl apply -f blue_deployment.yaml

echo "Applying Green Deployment..."
kubectl apply -f green_deployment.yaml

echo "Checking if pods are running..."
kubectl get pods -l app=messaging-app

echo "Deployments overview:"
kubectl get deployments -l app=messaging-app

GREEN_POD=$(kubectl get pods -l version=green -o jsonpath="{.items[0].metadata.name}")

echo "Checking logs for Green Deployment..."
kubectl logs "$GREEN_POD" || echo "No logs found for green deployment yet."

echo "Blue-Green deployment applied successfully."
